### ISSUE TITLE
Persistence

### ISSUE THREAD

**Issue by PatchRequest** [EveronLife/EveronLife#1]
**Summarize your proposal**
Storing data persistently is needed for nearly everything, therefore we need it too.

**Describe the solution you'd like**
The goal is to have a generic way to establish persistence for different components.
It has to provide a public interface for other components to store and load data without any knowledge about the technical implementation.

**Describe alternatives you've considered**
There are multiple possible technical implementation which have to be discussed.

**Comment by Jaccodouma** [comment]
It might be worth making a distinction between data dat needs to be saved for "proper" persistence (ie player money, roles/ranks/jobs etc) or stuff that isn't *that* imporant like vehicle positions, crop growth state etc., data that really needs to go from server shutdown to startup. Imo player money etc should be on a proper database, but a fair bit of persistence related things could just be a json dump that gets loaded & initialized on server start. 

A very janky solution could be to treat a certain folder as an endpoint. The reforger server writes "requests" to a json file, which gets a response in the form of another file being created by some server that at some point will instead open up a HTTP endpoint.

**Comment by Arkensor** [comment]
> It might be worth making a distinction between data dat needs to be saved for "proper" persistence (ie player money, roles/ranks/jobs etc) or stuff that isn't that imporant like vehicle positions, crop growth state etc., data that really needs to go from server shutdown to startup. Imo player money etc should be on a proper database, but a fair bit of persistence related things could just be a json dump that gets loaded & initialized on server start.

There I would not force separate these things. We could maybe have it so that different prefabs configure which storage backend they use, so player data is exclusively in the db, and other world states only local on disk that can be "lost" or whatever. But we should build it in a way that everything can be in either one storage backend.


> A very janky solution for interacting with an external server could be to treat a certain folder as an endpoint. The reforger server writes "requests" to a json file, which gets a response in the form of another file being created by some server that at some point will instead open up a HTTP endpoint.

Not sure how well this integrates with console hosting. I have no info yet if you can host a server on your own servers and then have console players connect to it. But tbh, we can probably wait for them to just fix the API. I have created a system as you describe for DayZ. See https://github.com/Arkensor/DayZServicePipeline for reference.

**Comment by Kapppa** [comment]
One thing I would like to add, with large JSON files on disk these can cause some issues. I have ran/developed game servers for multiple different games and this was always an issue. The main issue is that when updating a single users info we need to now write the whole JSON file again. This isn't really an issue with small amounts of data. But once the data gets large enough it be a big bottleneck.

Example, as we don't want dupes or data inconsistency we need to save basically every time an action in game happens. Lets say I am a player and I withdraw some money but its not enough so now I click withdraw 10 times to get the right amount. I have now we have written the JSON files 11 times. Lets say it is 10 - 20 mb that is a lot write time. This will be a big issue on large servers.

I'm not saying we shouldn't use JSON files as this would make testing easier as a database won't be needed. But we would need an alternative for larger servers. With the HTTP library being broke ATM, we can't do much about this issue at the present time. But what needs to be done is to make adding support for different persistent modules. So creating an interface that implements all of the methods for data persistence is needed. Then we can integrate any method we would like.

**Comment by MrPentha** [comment]
Yes we should look out for Database possibilities. I think a REST API is a bit overkill between Server and Database. We should check if there is a way to load Extensions, from which we can send SQL Querys to a SQL Server.

**Comment by Jaccodouma** [comment]
You could have some set folder structure as "tables" instead of a massive json file, splitting the data into relatively small json files and allowing modules to have their own file etc, giving a bunch of flexibility. 
```
📂/
  📂players
    📂{player_id}
      📄{player_idjson
      📄licenses.json
      📄vehicles.json
  📂groups
    📂{group_id}
      📄members.json
```

**Comment by Arkensor** [comment]
@Jaccodouma yeah individual files instead of one big massive one was where I was going anyway. I am currently thinking about if the framework needs to provide rolling versions or if this is the job of a backup system to copy out a dump of the persistence every x time interval.

**Comment by Jaccodouma** [comment]
I doubt rolling versions would be necessary or worth the effort right? What would be the goal? I imagine backups will work just fine, and with maybe some logging admins could manually rectify things if that'd be necessary.

**Comment by Arkensor** [comment]
> Yes we should look out for Database possibilities. I think a REST API is a bit overkill between Server and Database. We should check if there is a way to load Extensions, from which we can send SQL Querys to a SQL Server.

Regarding this, there are only two possibilities that we know of right now. FileIO (on the authority) and Web API on all instances. A named pipe to communicate with native support executables on the authority could work, but that will be much more hassle than either of the other options. There are no intended ways to load extensions (dll, so) and from early feedback from BI, there will never be (security).

**Comment by Arkensor** [comment]
> I doubt rolling versions would be necessary or worth the effort right? What would be the goal? I imagine backups will work just fine, and with maybe some logging admins could manually rectify things if that'd be necessary.

You are probably right, I was just throwing the thought out there. If anything the backups can be a separate feature that might not even be managed through the game itself. We technically could add it, but it would not affect the structure much of how persistency is done.

I will later post a PoC or diagram for my persistence draft. We can soon expect the fixed rest API to be included in an update and also easier access to the player id in the workbench. So I do not need to deal with any workarounds for that anymore. Makes things much easier :)

**Comment by DjCtavia** [comment]
I join @Jaccodouma on the file system, it's something I've also thought this way. It's not the best, but it works.
Doing it with the file/folder architecture will save us time later on the design for endpoint documentation if we decide to use a REST API.

For file backup, I may have something to share but the best thing would be to discuss it together in voice.

**Comment by ThibaudetTevai** [comment]
A friend which dev. on FiveM use a method to avoid multiple read and write on the database and improve the server performances :

For variables that are used multiple times, the solution is to store them in a .json file.
This file will be saved in the DB before the server restarts.

+1 for @Jaccodouma file structure :)

At the moment i train on the REST API & Json & Char. datas.
I can store the datas ( ID , name , inventory .... ) on the DB.
If you want some help i'm here @Arkensor ;)

**Comment by johnytoxic** [comment]
I would like to add my 2 cents to the discussion.

First I'd like to reference the IPC proof-of-concept someone posted on the official Arma Discord server: https://github.com/CallMeMax/enfusion-pipe-ipc. This PoC uses named pipes to establish a connection between the Enfusion scripting runtime and an external application. I'm also working on a PoC implemented in C++ and using the native Win32 API. Unfortunately, I was not able to get this working, yet. This is mainly due to the limitations of Enfusion's `FileIO` API. At best, the scripts would need to re-open a file handle to read from a named pipe, each time.

I could not find any other IPC mechanism, which would work with Enfusion.

I think the file-backed approach really is looking promising. I would like to remind you that Enfusion also ships with a Serialization engine (which works on top of the file API). Please take this into consideration! It might or might not be faster than to parse or generate JSON each time.

In general, I think it would be best to have a generic interface for persistence. Maybe even on a higher level with something similar but not that extensive as ORM, or DAOs. Then there could be multiple persistance backends, independent of the data which needs to be persisted (e.g. JSON, Serialized, IPC, etc.).

**Comment by Arkensor** [comment]
Just as quick info because it is not known everywhere yet, the RestAPI is working so the first iteration of this will ship with a bare-bones web api setup as well. Regardless adding options via native serverside extensions should be working as well. We will need to see what is included with the base framework and what is maintained through a third-party addon maybe. We will see :)
